project:
  type: website
  output-dir: docs

website:
  title: "Cognitive Task Modeling"
  description: "Progress and report on the Forecasting Proficiency Test's cognitive task modeling work"
  site-url: "https://jhelmer3.github.io/cognitive-tasks/"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "Tasks"
        menu:
          - Reports/denominator-neglect_report.qmd
          - Reports/raven_report.qmd
          - Reports/decision-rules_report.qmd
          - Reports/bayesian-update_report.qmd
          - Reports/number-series_report.qmd
          - Reports/time-series_report.qmd
          - Reports/coherence-forecasting-scale_report.qmd
      - text: "Search Algorithms"
        menu: 
          - Reports/Search Algorithms/search_fpt-v2_report.qmd
          - Reports/Search Algorithms/search_fpt-v3_report.qmd
          - Reports/Search Algorithms/search_fpt-v4_report.qmd
          - Reports/Search Algorithms/search_fpt-v5_report.qmd
      - text: "LASSO"
        href: Reports/lasso.qmd
      - text: "Methods"
        menu:
          - Reports/Methods/2PL.qmd
    tools:
      - icon: github
        href: https://github.com/jhelmer3/cognitive-tasks
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

format:
  html:
    theme: 
      - cosmo.scss
    css: styles.css
    toc: true
