---
title: "Method Comparison"
subtitle: "Search algorithm, ridge regression, and XGBoost"
date: last-modified
toc: true
format: 
  html:
    code-fold: true
    grid: 
      margin-width: 350px
      gutter-width: 1em
author: Jessica Helmer
knitr:
    opts_chunk: 
      dev: png
      dev.args:
        bg: transparent
html-table-processing: none
self-contained: true
---

::: panel-tabset
#### Setup

```{r}
#| message: false
#| code-fold: show
library(tidyverse)
library(gt)
```

#### Reading

```{r}
#| code-fold: show
v5_dat <- readRDS(here::here("Data", "v5_dat.rds"))

v5 <- readRDS(here::here("Data", "Search Algorithms", "v5test_dat.rds"))
xgb <- readRDS(here::here("Data", "xgboost", "xgb_item-importance.rds"))
ridge <- readRDS(here::here("Data", "ridge_regression.rds"))

startup_costs <- readRDS(here::here("Data", "startup_costs.rds"))

if (!dir.exists(here::here("Data", "Method Comparison"))) dir.create(here::here("Data", "Method Comparison"))
```

#### Functions

```{r}
#| code-fold: show
source(here::here("Scripts", "get_startup.R"))
source(here::here("Scripts", "j_gt.R"))
```

#### Cleaning
```{r}
methods <- list("v5", "ridge", "xgb")

v5_ranked <- v5 |> 
  select(item, v5_rank = rep) |>
  arrange(v5_rank)

xgb_ranked <- xgb |>
  # because higher importance should correspond to lower (better) rank
  # adding one to match v5
  mutate(xgb_rank = n() - rank(Importance) + 1) |>
  select(xgb_rank, item = Variable) |>
  arrange(xgb_rank)

ridge_ranked <- ridge |>
  mutate(ridge_rank = n() - rank(Importance) + 1) |>
  select(ridge_rank, item = Variable) |>
  arrange(ridge_rank)

ranks <- v5_ranked |>
  full_join(xgb_ranked,
            by = "item") |>
  full_join(ridge_ranked,
            by = "item") |>
  inner_join(v5_dat |>
               select(task, item, time) |>
               unique(),
             by = "item")
```
:::


## Method Comparison

Correlations between item ranks from each method.

:::: {.columns}
::: {.column width="50%"}
Spearman Rank

```{r}
ranks |>
  select(`Search Algorithm` = v5_rank,
         `XGBoost` = xgb_rank,
         `Ridge` = ridge_rank) |>
  cor(method = "spearman") |>
  as.data.frame() |>
  rownames_to_column() |>
  j_gt()
```
:::

::: {.column width="50%"}
Kendall's Tau

```{r}
ranks |>
  select(`Search Algorithm` = v5_rank,
         `XGBoost` = xgb_rank,
         `Ridge` = ridge_rank) |>
  cor(method = "kendall") |>
  as.data.frame() |>
  rownames_to_column() |>
  j_gt()
```
:::
::::


```{r}
#| layout-ncol: 3
#| column: page
ranks |>
  mutate(task = str_split_i(item, "_", 1)) |>
  ggplot(aes(x = v5_rank, y = xgb_rank, label = item, color = task)) +
  geom_text()

ranks |>
  mutate(task = str_split_i(item, "_", 1)) |>
  ggplot(aes(x = v5_rank, y = ridge_rank, label = item, color = task)) +
  geom_text()

ranks |>
  mutate(task = str_split_i(item, "_", 1)) |>
  ggplot(aes(x = ridge_rank, y = xgb_rank, label = item, color = task)) +
  geom_text()
```

### Method Timing

```{r}
walk(methods, \(x) ranks |>
      mutate(task = str_split_i(item, "_", 1)) |>
      arrange(paste0(x, "_rank") |> sym() |> eval()) |>
      mutate(.by = task,
             time_w_startup = time + ifelse(item == first(item), get_startup(first(task)), 0)) |>
      mutate(cum_time = cumsum(time_w_startup)) |>
      assign(x = paste0(x, "_ranks_w_timing"), value = _, env = globalenv()))
```


:::: {.columns .column-page}
::: {.column width="33%"}
```{r}
#| eval: true
v5_r2_w_time <- map(1:99,
    \(i) {
      included_items <- v5_ranks_w_timing |>
        select(item, task, v5_rank, cum_time) |>
        head(i)
      
      inner_join(v5_dat|>
                   select(subject_id, sscore, item, score),
                 included_items,
                 by = "item") |>
        summarize(.by = c(subject_id, task),
                  sscore = first(sscore),
                  score = mean(score)) |>
        mutate(formula = paste("sscore ~", task |> unique() |> paste(collapse = "+"))) |>
        pivot_wider(names_from = task, values_from = score) |>
        drop_na() |>
        summarize(rep = i,
                  item = included_items |> filter(cum_time == max(cum_time)) |> pull(item),
                  test_r2 = summary(lm(as.formula(first(formula)),
                                       data = pick(everything())))$r.squared,
                  cum_time = included_items |> filter(cum_time == max(cum_time)) |> pull(cum_time))}) |>
  list_rbind()

saveRDS(v5_r2_w_time, here::here("Data", "Method Comparison", "v5_r2_w_time.rds"))
```
:::

::: {.column width="33%"}
```{r}
#| eval: true
xgb_r2_w_time <- map(1:99,
    \(i) {
      included_items <- xgb_ranks_w_timing |>
        select(item, task, v5_rank, cum_time) |>
        head(i)
      
      inner_join(v5_dat |>
                   select(subject_id, sscore, item, score),
                 included_items,
                 by = "item") |>
        summarize(.by = c(subject_id, task),
                  sscore = first(sscore),
                  score = mean(score)) |>
        mutate(formula = paste("sscore ~", task |> unique() |> paste(collapse = "+"))) |>
        pivot_wider(names_from = task, values_from = score) |>
        drop_na() |>
        summarize(rep = i,
                  item = included_items |> filter(cum_time == max(cum_time)) |> pull(item),
                  test_r2 = summary(lm(as.formula(first(formula)),
                                       data = pick(everything())))$r.squared,
                  cum_time = included_items |> filter(cum_time == max(cum_time)) |> pull(cum_time))}) |>
  list_rbind()

saveRDS(xgb_r2_w_time, here::here("Data", "Method Comparison", "xgb_r2_w_time.rds"))
```
:::

::: {.column width="33%"}
```{r}
#| eval: true
ridge_r2_w_time <- map(1:99,
    \(i) {
      included_items <- ridge_ranks_w_timing |>
        select(item, task, v5_rank, cum_time) |>
        head(i)
      
      inner_join(v5_dat|>
                   select(subject_id, sscore, item, score),
                 included_items,
                 by = "item") |>
        summarize(.by = c(subject_id, task),
                  sscore = first(sscore),
                  score = mean(score)) |>
        mutate(formula = paste("sscore ~", task |> unique() |> paste(collapse = "+"))) |>
        pivot_wider(names_from = task, values_from = score) |>
        drop_na() |>
        summarize(rep = i,
                  item = included_items |> filter(cum_time == max(cum_time)) |> pull(item),
                  test_r2 = summary(lm(as.formula(first(formula)),
                                       data = pick(everything())))$r.squared,
                  cum_time = included_items |> filter(cum_time == max(cum_time)) |> pull(cum_time))}) |>
  list_rbind()

saveRDS(ridge_r2_w_time, here::here("Data", "Method Comparison", "ridge_r2_w_time.rds"))
```
:::
::::

```{r}
#| column: page
#| layout-ncol: 3
v5_r2_w_time <- readRDS(here::here("Data", "Method Comparison", "v5_r2_w_time.rds"))
xgb_r2_w_time <- readRDS(here::here("Data", "Method Comparison", "xgb_r2_w_time.rds"))
ridge_r2_w_time <- readRDS(here::here("Data", "Method Comparison", "ridge_r2_w_time.rds"))

walk2(list(v5_r2_w_time, xgb_r2_w_time, ridge_r2_w_time),
      list("Search Algorithm", "XGBoost", "Ridge"),
      \(d, name) (d |>
                    mutate(task = str_split_i(item, "_", 1)) |>
                    ggplot(aes(x = cum_time, y = test_r2)) +
                    geom_line() +
                    geom_point(aes(color = task)) +
                    coord_cartesian(ylim = c(.1, .5)) +
                    labs(title = name, y = "R<sup>2</sup>", x = "Time") +
                    theme(axis.title.y = ggtext::element_markdown())) |>
        print())
```

```{r}
#| layout-ncol: 2
v5_ranks_w_timing |>
  filter(cum_time <= 15) |>
  count(task, name = "v5") |>
  full_join(xgb_ranks_w_timing |>
              filter(cum_time <= 15) |>
              count(task, name = "xgb"),
            by = "task") |>
  full_join(ridge_ranks_w_timing |>
              filter(cum_time <= 15) |>
              count(task, name = "ridge"),
            by = "task") |>
  arrange(task) |>
  j_gt(rowname_col = "task") |>
  sub_missing(missing_text = "") |>
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_column_labels())

v5_ranks_w_timing |>
  filter(cum_time <= 15) |>
  count(task, name = "v5") |>
  full_join(xgb_ranks_w_timing |>
              filter(cum_time <= 15) |>
              count(task, name = "xgb"),
            by = "task") |>
  full_join(ridge_ranks_w_timing |>
              filter(cum_time <= 15) |>
              count(task, name = "ridge"),
            by = "task") |>
  mutate(task = str_split_i(task, "\\.", 1)) |>
  summarize(.by = task,
            across(everything(), ~ sum(.x, na.rm = T))) |>
  arrange(task) |>
  j_gt(rowname_col = "task") |>
  sub_missing(missing_text = "") |>
  sub_zero(zero_text = " ") |>
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_column_labels())
```

### Item Counts Across Tests
```{r}
walk(methods, \(x) x |>
      paste0("_ranks_w_timing") |>
      sym() |>
      eval() |>
      filter(cum_time <= 15) |>
      pull(item) |>
      assign(x = paste0(x, "_test"),
             value = _,
             env = globalenv()))

ranks |>
  pull(item) |>
  map(\(item) tibble(item = item,
                     count = sum(c(item %in% v5_test,
                                   item %in% xgb_test,
                                   item %in% ridge_test)))) |>
  bind_rows() |>
  filter_out(count == 0) |>
  arrange(desc(count)) |>
  mutate(task = str_split_i(item, "_", 1),
         .before = item)  |>
  j_gt(rowname_col = c("task", "item")) |>
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_column_labels()) |>
  fmt_number(count, decimals = 0)
```



```{r}
item_properties <- rbind(
  readRDS(here::here("Data", "Denominator Neglect", "dn_dat_c.rds")) |>
    select(item, choice_type, proportion_difference, small_lottery_gold_prop) |>
    unique() |>
    left_join(readRDS(here::here("Data", "Denominator Neglect", "top_items.rds")) |> 
                select(rank, conf_item, harm_item) |>
                pivot_longer(c(conf_item, harm_item),
                             names_to = "choice_type", values_to = "item") |>
                select(-choice_type),
              by = "item") |>
    mutate(item_ct = paste0("dn.c_", rank, "_", choice_type),
           item = paste0("dn.c_", rank),
           .keep = "unused") |>
    nest(.by = item, properties = !item) ,
  
  readRDS(here::here("Data", "Denominator Neglect", "dn_dat_s.rds")) |>
    select(item, choice_type, proportion_difference, small_lottery_gold_prop) |>
    unique() |>
    left_join(readRDS(here::here("Data", "Denominator Neglect", "top_items_s.rds")) |> 
                select(rank, conf_item, harm_item) |>
                pivot_longer(c(conf_item, harm_item),
                             names_to = "choice_type", values_to = "item") |>
                select(-choice_type),
              by = "item") |>
    mutate(item_ct = paste0("dn.s_", rank, "_", choice_type),
           item = paste0("dn.s_", rank),
           .keep = "unused") |>
    nest(.by = item, properties = !item),
  
  readRDS((here::here("Data", "Bayesian Update", "bu_dat_e.rds"))) |>
    mutate(item = paste0("bu.e_", unique_trial)) |>
    select(item, ball_split) |>
    unique() |>
    nest(properties = !c(item)),
  
  readRDS((here::here("Data", "Bayesian Update", "bu_dat_h.rds"))) |>
    mutate(item = paste0("bu.h_", unique_trial)) |>
    select(item, ball_split) |>
    unique() |>
    nest(properties = !c(item)),
  
  readRDS(here::here("Data", "ADMC Decision Rules", "admc.dr_dat.rds")) |>
    mutate(item = paste0("admc.dr_", parse_number(admc_id))) |>
    select(item, n_correct_options) |>
    unique() |>
    nest(properties = !c(item)),
  
  readRDS(here::here("Data", "Time Series", "ts_dat.rds")) |>
    mutate(item = paste0("ts_", ts_id)) |>
    select(item, noise = noise_condition, datapoints, func, direction) |>
    unique() |>
    nest(properties = !c(item)),
  
  readRDS(here::here("Data", "Number Series", "ns_dat.rds")) |>
    mutate(number_series = recode_values(parse_number(ns_id),
                                         1 ~ "10, 4, ____, -8, -14, -20",
                                         2 ~ "3, 6, 10, 15, 21, ____",
                                         3 ~ "121, 100, 81, ____, 49",
                                         4 ~ "3, 10, 16, 23, ____, 36",
                                         5 ~ "3/21, ____, 13/11, 18/6, 23/1, 28/-4",
                                         6 ~ "200, 198, 192, 174, ____",
                                         7 ~ "3, 2, 10, 4, 19, 6, 30, 8, ____",
                                         8 ~ "10000, 9000, ____, 8890, 8889",
                                         9 ~ "3/4, 4/6, 6/8, 8/12, ____")) |>
    select(item = ns_id, number_series) |>
    unique() |>
    nest(properties = !c(item))
)

```


```{r}
#| column: page
#| layout-ncol: 3
v5_candidate_test <- tibble(item = sym(paste0("v5", "_test")) |> eval()) |>
         left_join(item_properties,
                   by = "item") |>
         arrange(item) |>
         pmap(\(item, properties) tibble(item, properties) |>
                unnest(cols = c()) |>
                mutate(item = ifelse(str_detect(item, "dn"), item_ct, item),
                       .keep = "unused") |>
                nest(properties = !item)) |>
         list_rbind() |>
         j_gt() |>
         tab_header("Search Algorithm")

ridge_candidate_test <- tibble(item = sym(paste0("ridge", "_test")) |> eval()) |>
         left_join(item_properties,
                   by = "item") |>
         arrange(item) |>
         pmap(\(item, properties) tibble(item, properties) |>
                unnest(cols = c()) |>
                mutate(item = ifelse(str_detect(item, "dn"), item_ct, item),
                       .keep = "unused") |>
                nest(properties = !item)) |>
         list_rbind() |>
         j_gt() |>
         tab_header("Ridge")

xgboost_candidate_test <- tibble(item = sym(paste0("xgb", "_test")) |> eval()) |>
         left_join(item_properties,
                   by = "item") |>
         arrange(item) |>
         pmap(\(item, properties) tibble(item, properties) |>
                unnest(cols = c()) |>
                mutate(item = ifelse(str_detect(item, "dn"), item_ct, item),
                       .keep = "unused") |>
                nest(properties = !item)) |>
         list_rbind() |>
         j_gt() |>
         tab_header("XGBoost")

saveRDS(v5_candidate_test, here::here("Data", "Method Comparison", "v5_candidate_test.rds"))
saveRDS(ridge_candidate_test, here::here("Data", "Method Comparison", "ridge_candidate_test.rds"))
saveRDS(xgboost_candidate_test, here::here("Data", "Method Comparison", "xgboost_candidate_test.rds"))

v5_candidate_test
ridge_candidate_test
xgboost_candidate_test
```


```{r}
map(c("v5", "ridge", "xgb"), \(test_data_name) test_data_name |>
      paste0("_r2_w_time") |>
      sym() |>
      eval() |>
      filter(cum_time <= 15) |>
      filter(cum_time == max(cum_time)) |>
      select(test_r2) |>
      mutate(method = test_data_name)) |>
  list_rbind() |>
  pivot_wider(names_from = method, values_from = test_r2) |>
  j_gt() |>
  cols_label(v5 = "Search",
             ridge = "Ridge",
             xgb = "XGBoost") |>
  tab_header(md("$R^2$ of Each Test"))
```


```{r}
n_bootstraps <- 200

bootstrapped_r2 <- map(c("v5", "ridge", "xgb"), \(test_data_name) {
  test_data <- test_data_name |>
    paste0("_r2_w_time") |>
    sym() |>
    eval()
  
  test_15_min_items <- test_data |>
    filter(cum_time <= 15) |>
    pull(item)
  
  test_15_min_dat <- v5_dat |>
    filter(item %in% test_15_min_items) |>
    summarize(.by = c(subject_id, task),
              sscore = first(sscore),
              score = mean(score)) |>
    mutate(formula = paste("sscore ~", task |> unique() |> paste(collapse = "+"))) |>
    pivot_wider(names_from = task, values_from = score) |>
    drop_na()
  
  map(1:n_bootstraps, \(i)
      test_15_min_dat |>
        slice_sample(n = nrow(test_15_min_dat), replace = T) |>
        summarize(test = test_data_name,
                  bootstrap_id = i,
                  test_r2 = summary(lm(as.formula(first(formula)),
                                       data = pick(everything())))$r.squared)) |>
    list_rbind()
}
) |> list_rbind()

r2s_plts <- patchwork::wrap_plots(
  bootstrapped_r2 |>
  ggplot(aes(x = test_r2, y = test, fill = test)) +
  ggridges::geom_density_ridges() +
    theme(aspect.ratio = 1/1.5),
  
  bootstrapped_r2 |>
  mutate(test_r2_z = (test_r2 - mean(test_r2)) / sd(test_r2)) |>
  ggplot(aes(x = test_r2_z, y = test, fill = test)) +
  ggridges::geom_density_ridges() +
    theme(aspect.ratio = 1/1.5), 
  guides = "collect"
)

r2s_plts
saveRDS(r2s_plts, here::here("Figures", "r2s_plts"))


bootstrapped_r2 |>
  lm(test_r2 ~ test, data = _) |>
  anova()

cohens_ds <- bootstrapped_r2 |>
  select(test1 = test) |>
  unique() |>
  crossing(test2 = bootstrapped_r2 |>
             pull(test) |>
             unique()) |>
  filter_out(test1 == test2) |>
  pmap(
    \(test1, test2) {
      d <- bootstrapped_r2 |>
        filter(test == test1 | test == test2)
      
      d |>
        summarize(test1 = test1,
                  test2 = test2,
                  cohens_d = effectsize::cohens_d(test_r2 ~ test, data = d)$Cohens_d)
    }
  ) |>
  list_rbind()

cohens_ds |>
  ggplot(aes(x = test1, y = test2, alpha = cohens_d)) +
  geom_tile(show.legend = F, fill = "orange2") +
  geom_text(aes(label = round(cohens_d, 2)), alpha = 1) +
  scale_alpha_continuous(range = c(0, max(cohens_ds$cohens_d))) +
  theme(aspect.ratio = 1)
```


